[package]
name = "pixelfield"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
png = { version = "0.17" }
sdl2 = { version = "0.35" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
